# SubCheck 精简配置
timeout: 5000           # 超时时间(毫秒)
concurrent: 10          # 并发测试数
min_speed: 1            # 最低速度要求(Mbps)
max_latency: 1000       # 最大延迟(毫秒)

# 网络优化
dns_servers:
  - 8.8.8.8
  - 1.1.1.1
  - 114.114.114.114

# 测速设置
speed_test:
  enabled: true
  test_file_size: 100   # 测试文件大小(KB)
  timeout: 10           # 测速超时(秒)