# SubCheck 配置文件

# 测试间隔 (秒)
interval: 3600

# 最大测试节点数
max_nodes: 20

# 超时设置
timeout:
  connect: 10
  total: 30

# 代理设置
proxy:
  socks_port: 10808
  
# 测试设置
test:
  speed_test_size: 1048576  # 1MB
  max_concurrent: 3
  retry_count: 2

# 日志设置
log:
  level: info
  file: subcheck.log